In [3]:
import numpy as np

my_array = np.arange(1000000)
my_list = list(range(100000))

In [ ]:
%timeit my_list2 = [i *2 for i in my_list]
%timeit my_array2 = my_array * 2

In [4]:
a = [
    [1, 1.2, 3,],
    [-123, 123,0]

    
]
data = np.array(a)
print(data)


[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [5]:
print(data * 10)  #0차원 스칼라(scala) , 1차원은 벡터(vector)  
                # 2차원은 행렬, 메트릭스(matrix)  3차원 이상을 텐서로 (tenser)

[[   10.    12.    30.]
 [-1230.  1230.     0.]]


In [6]:
print(data.shape)   # 가로 세로의 길이 (가장 큰 단위의 갯수)
print(data.dtype)   #데이터의 세부 데이터 , 전부다 소수이기때문에 float

(2, 3)
float64


## ndarray 생성하기 

In [7]:
data1 = [1, 2, 3, 4, 5]
array1 = np.array(data1)
print(array1)
print(type(array1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
arr2 = np.array([[1.1, 2.2, 3.3], [5.5, 4.4, 7.7]])
print(arr2)
print(type(arr2))

[[1.1 2.2 3.3]
 [5.5 4.4 7.7]]
<class 'numpy.ndarray'>


In [18]:
print(array1.ndim)
print(arr2.ndim)

1
2


In [22]:
print(np.zeros(10))
print([0] * 10)
print(np.zeros((5,5)))  # 배열을 편하게 망들어
print(np.empty((2,2,2)))  #메모리에 할당 안댕, 빈칸 넣어

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [23]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## ndarray 자료형

In [27]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr2 = np.array([1, 2, 3], dtype = np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [30]:
arr1 = np.array([1, 2, 3])
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64)
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [31]:
arr2 = np.array([1,1,  2.2,  9.9])
int_arr2 = arr2.astype(np.int64)
print(int_arr2)
print(int_arr2.dtype)

[1 1 2 9]
int64


##  산술연산

In [37]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr * arr)
print(arr + arr)
print(1 / arr)
print( arr ** 3)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [39]:
arr2 = np.array([[3,2,1],[1,2,3]])
print(arr1, arr2)
print(arr1 > arr2)
print(arr1 == 3)

[[1 2 3]
 [4 5 6]] [[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False False  True]
 [False False False]]


## 색인과 슬라이싱

In [40]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
arr[5]
print(arr[2:5])

[2 3 4]


In [44]:
arr[2:5] = 10   #모든 범위에 하나씩 대입 되는 , 스칼라,,,,잘라진 데이터를 바꿨는데 원본이 같이 바뀜
print(arr)     #원본에 반영 되어,,,요,,,

[ 0  1 10 10 10  5  6  7  8  9]


In [46]:
py_list = [1,2,3,4,5]
py_list[2:3].pop()
print(py_list)

[1, 2, 3, 4, 5]


In [47]:
# 2 차원 배열의 접금

arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [50]:
print(arr[1][1]
     )

5


In [52]:
print(arr[1,1])

5


In [54]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
          [[11,12,13],[14,15,16],[17,18,19]],
          [[11,22,33],[44,55,66],[77,88,99]]])

In [60]:
print(arr3d[2][0][1])
print(arr3d[2,0,1])

22
22


In [61]:
# 슬라이싱

In [65]:
arr3d[:1,1:,2:] 

array([[[6],
        [9]]])

In [66]:
arr3d[:1,1:,2:] = 9999
print(arr3d)      # 원본의 데이터도 수정이 된다

[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  11   12   13]
  [  14   15   16]
  [  17   18   19]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]]]


### 불리언 값으로 선택

In [70]:
names =np.array(['hong', 'kim', 'hong', 'kim'])
data =np.array([['math', 60],['math',90],['english', 70],['english', 50]])


In [71]:
names == 'hong'

array([ True, False,  True, False])

In [73]:
data[names == 'hong']  # 특정 조건의 데이터를 구할때
#data[True, False, True, False]

array([['math', '60'],
       ['english', '70']], dtype='<U21')

In [76]:
print(data[names == 'hong',:1]) # 인덱스 접근
print(data[names == 'hong', 1])  # 슬라이싱 접근 

[['math']
 ['english']]
['60' '70']


In [79]:
print(names != 'hong')
print(~(names == 'hong'))   # ~를 이용해서 보여줌 


[False  True False  True]
[False  True False  True]


In [80]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['english', '50']], dtype='<U21')

## 팬시 색인 (fancy indexing)

In [82]:
arr = np.zeros((8,4))
for i in range(8):
    arr[i]= i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [84]:
arr[[4, 3, 0, 5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [85]:
arr[[-3,-5,-1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [87]:
arr = np.arange(32).reshape(8, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [88]:
arr[[1, 5], [2, 3]]    # 첫번째 다섯번째 줄에서 2번 3번 것의 값

array([ 6, 23])

In [90]:
arr[[1, 5]][:,[2, 3]]   # 같은 것 

array([[ 6,  7],
       [22, 23]])

##  배열전치

In [91]:
arr = np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [92]:
print(arr.T)   # 행렬에서의 전치 , 사선으로 나눠서 축을 바꿀 때

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [94]:
print(arr @ arr.T )  #  행렬의 곱 연산 , 행렬의 내적, 곱
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## numpy 함수

In [97]:
samples = np.random.standard_normal(size =(3,3))
print(samples)

[[-0.77926417  1.40208922 -0.41061785]
 [ 1.25954978 -1.59110698 -1.04011837]
 [-1.15977271  0.90951664 -1.10191944]]


In [100]:
arr1 = np.sqrt(samples)   # 루트로 만들어 주는 것 nan = 숫자가 아닙니다!
print(arr1)

[[       nan 1.18409848        nan]
 [1.12229665        nan        nan]
 [       nan 0.95368582        nan]]


/var/folders/cw/vfz1c_rj2vg143pfdts65w400000gn/T/ipykernel_39232/949972240.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples)   # 루트로 만들어 주는 것 nan = 숫자가 아닙니다!


In [101]:
arr2 = np.abs(samples)     # 절댓값으로 바꿔 주는 함수라고 할 수 이쯤
print(arr2)     

[[0.77926417 1.40208922 0.41061785]
 [1.25954978 1.59110698 1.04011837]
 [1.15977271 0.90951664 1.10191944]]


In [102]:
np.isnan(arr1)

array([[ True, False,  True],
       [False,  True,  True],
       [ True, False,  True]])