# numpy & pandas

## 01 numpy
 

In [ ]:
`import numpy as np`

- numpy를 np로 줄여서 부르겠다는 말
- 사용하는 이유는 : 실행 속도와 , 다차원의 구조를 
  쉽게 처리 하기 위해서 이다 
- 차원에 따라 부르는 이름이 다르다.
  0차원 스칼라 : scala
  1차원 벡터 : vector 
  2차원 행렬 : matrix
  3차원 이상 : tenser

`print(data.dtype)`을 하게 될 경우 , 세부 데이터가 가진 타입을 전부다 보여준다
`print(data.shape)`의 경우 행렬의 세로와 가로를 보여줌 ..?

## ndarray 생성하기 

- ndarry는 N차원 배열 객체이다
- 하나의 데이터 타입만 넣을 수 있다


In [2]:
import numpy as np

In [3]:
data1 = [1, 2, 3, 4, 5]
array1 = np.array(data1)
print(array1)
print(type(array1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr2 = np.array([[1.1, 2.2, 3.3], [5.5, 4.4, 7.7]])
print(arr2)
print(type(arr2))

[[1.1 2.2 3.3]
 [5.5 4.4 7.7]]
<class 'numpy.ndarray'>


In [5]:
print(array1.ndim)
print(arr2.ndim)

1
2


- ndim의 경우 array의 차원을 알려줌
  

#### 편하게 배열을 만드는 방법

In [7]:
print(np.zeros(10))
print([0] * 10)
print(np.zeros((5,5)))  #5*5로 마들어 
print(np.empty((2,2,2)))  # 2개씩 2들 있는 걸
                            # 두개 만들어

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [12]:
print(np.empty((2,2,2)))

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


## ndarray 자료형

In [13]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr2 = np.array([1, 2, 3], dtype = np.int32)


In [14]:

print(arr1.dtype)
print(arr2.dtype)

float64
int32


- 각각의 타입을 float으로 /int로 자신이 원하는 방식으로 만들 수 있다.

In [15]:
arr1 = np.array([1, 2, 3])
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64)
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


- astype 또한 형변환을 도와줌

##  산술연산
- 파이썬 기본 규칙과 마찬가지로 산술연산이 가능 하다

In [18]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr + arr)
print(1 / arr)
print( arr ** 3)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [19]:
print(arr * arr)

[[ 1  4  9]
 [16 25 36]]


- 곱하기의 걍우 각 행의 자리에 맞게 곱한다고 생각 하면 된다!
- 1*1, 4*4 그래서 제곱수의 값이 결과로 나타난 것이라고 생각 하는 것이 쉽다

In [20]:
arr2 = np.array([[3,2,1],[1,2,3]])
print(arr1, arr2)
print(arr1 > arr2)
print(arr1 == 3)

[[1 2 3]
 [4 5 6]] [[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False False  True]
 [False False False]]


## 색인과 슬라이싱

In [21]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


- 기존의 사칙연산과 동일한 방법으로 색인과 슬라이싱을 할 수 있다

In [23]:
print(arr[5]) #5번째 자리
print(arr[2:5]) #2자리에서 5번째 전까지

5
[2 3 4]


In [24]:
arr[2:5] = 10   
print(arr) 

[ 0  1 10 10 10  5  6  7  8  9]


- 설정한 모든 범위의 데이터가 변화 된다

### 2차원 배열의 접근

In [25]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [26]:
print(arr[1][1])
# = print(arr[1,1]) -> 조금 더 직관적

5


- 에레이의 첫번째 [1]에 [1]번의 값에 접근해줘
- 

### 3차원의 접근
- 동일 하다, 하나씩 찾아 들어 가는 방시으로 접근 하면 된다링

In [27]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
          [[11,12,13],[14,15,16],[17,18,19]],
          [[11,22,33],[44,55,66],[77,88,99]]])

In [28]:
print(arr3d[2][0][1])
print(arr3d[2,0,1])

22
22


## 슬라이싱

In [29]:
arr3d[:1,1:,2:] 

array([[[6],
        [9]]])

- 첫번째 줄 까지 중에서, 1번 부터 시작

In [30]:
arr3d[:1] 

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [31]:
arr3d[:1,1:] 


array([[[4, 5, 6],
        [7, 8, 9]]])

In [32]:
arr3d[:1,1:,2:] 

array([[[6],
        [9]]])

In [33]:
arr3d[:1,1:,2:] = 9999
print(arr3d) 

[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  11   12   13]
  [  14   15   16]
  [  17   18   19]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]]]


## 불리언 값으로 선택

In [35]:
names =np.array(['hong', 'kim', 'hong', 'kim'])
data =np.array([['math', 60],['math',90],['english', 70],['english', 50]])


In [36]:
names == 'hong'

array([ True, False,  True, False])

In [37]:
data[names == 'hong'] 

array([['math', '60'],
       ['english', '70']], dtype='<U21')

In [38]:
print(names != 'hong')
print(~(names == 'hong'))   # ~를 이용해서  반대의 경우를보여줌 


[False  True False  True]
[False  True False  True]


## 팬시 색인 (fancy indexing)¶

In [40]:
arr = np.zeros((8,4))
for i in range(8):
    arr[i]= i
print(arr)
print(arr[[4, 3, 0, 5]])
print(arr[[-3,-5,-1]])  # 음수 인덱싱 가능

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [5. 5. 5. 5.]]
[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [7. 7. 7. 7.]]


In [41]:
arr = np.arange(32).reshape(8, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


-32개를 만드는뎅 8열 4행으로 만들어줘

In [42]:
print(arr.T)  
# 행렬에서의 전치 , 사선으로 나눠서 축을 바꿀 때

[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]


# pandas _series
- 판다스에서 사용하는 일차원의 배열
- index를 사용할 수 있음

In [43]:
import pandas as pd
import numpy as np

- 항상 함수를 불러 온 다음에 실행

In [44]:
arr = np.arange(100,110)
print(arr)

[100 101 102 103 104 105 106 107 108 109]


In [45]:
s = pd.Series(arr)  #class 이다요
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int64


- 시리즈는 항상 대문자 S를 사용,class의 개념과 비슷 함
- 엑셀과 마찬가지로 카테고리를 정하는 것임

In [46]:
s= pd.Series(['kim', 'lee' , 'park'])
print(s) 
s[2]

0     kim
1     lee
2    park
dtype: object


'park'

- 양수의 인덱싱만 적용 가능 하다

In [47]:
names = pd.Series(['kim','lee','park'], index = ['a','b','c'])

In [49]:
names['a']

'kim'

- 직접적으로 인덱싱을 부여 할 수 있음

## NaN(not a number)

In [50]:
s = pd.Series([1,2,3 ,np.nan])
print(s)

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64


직접적으로 숫자가 아닌 것을 부여 하여 만들 수 있다.

## fancy indexing

In [51]:
f = ['바나나', 'apple', 'grape', np.nan]
s = pd.Series(f,index =list('abcd'))
print(s)

a      바나나
b    apple
c    grape
d      NaN
dtype: object


In [52]:
s['a']
s[['d','a']]

d    NaN
a    바나나
dtype: object

## bool indexing


In [53]:
s = pd.Series([1,3, np.nan,10,11,np.nan])
print(s)

0     1.0
1     3.0
2     NaN
3    10.0
4    11.0
5     NaN
dtype: float64


In [54]:
s.isnull()  

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

숫자가 아는 것을 true로 분류 해줌

In [55]:
s.isna()

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [56]:
s[s.isnull()]  # 수가 아닌 것만 보여줌

2   NaN
5   NaN
dtype: float64

In [58]:
s[s.notnull()]  # 숫자인 것만 보여줌

0     1.0
1     3.0
3    10.0
4    11.0
dtype: float64

In [59]:
s[s.notna()]

0     1.0
1     3.0
3    10.0
4    11.0
dtype: float64

## slcing

In [62]:
s = pd.Series([1,2,3], index =list('abc'))

In [64]:
s[1:2]
s['a':'b']

a    1
b    2
dtype: int64

## dataframe

- 판다스에서 사용하는 2차원 데이터 구조
  (excel, sheet와 유사)
- 행(row), 열 (column)구조

In [65]:
d =pd.DataFrame([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
d

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [66]:
d = pd.DataFrame([
    [1,2,3],
    [4,5,6],
    [7,8,9],
], columns = ['가', '나', '다'])
d

가  나  다
0  1  2  3
1  4  5  6
2  7  8  9

- 열에 가나다를 부여

In [67]:
d = pd.DataFrame([
    [1,2,3],
    [4,5,6],
    [7,8,9],
], row = ['a','b','c'])
d

TypeError: DataFrame.__init__() got an unexpected keyword argument 'row'

- 안되는 이유는 row라는 값이 존재 하지 않으며 , 행은 index로 접근 하는 것이 맞음

In [68]:
info = {
    'name' : ['kim','lee','park'],
    'age' : [10, 20, 30]
}    # 길이가 맞아야 한다

In [69]:
info_df = pd.DataFrame(info)

In [71]:
print(info_df.columns)
print(info_df.values)

Index(['name', 'age'], dtype='object')
[['kim' 10]
 ['lee' 20]
 ['park' 30]]


In [72]:
info_df.T  #대칭도 가능 함유


0    1     2
name  kim  lee  park
age    10   20    30

### index 지정

In [73]:
info_df.index = list('abc')
info_df

name  age
a   kim   10
b   lee   20
c  park   30

### column 다루기

In [74]:
info_df.columns

Index(['name', 'age'], dtype='object')

In [75]:
print(info_df['name'] )  
print(type(info_df['name'] ))    

a     kim
b     lee
c    park
Name: name, dtype: object
<class 'pandas.core.series.Series'>


- 인덱스에 대한 접근이 같아 , 열에 대한 정보를 넣으면 해당 정보를 모두 불러 올 수 있음

In [76]:
info_df[     ['age','name']        ]  

age  name
a   10   kim
b   20   lee
c   30  park

In [78]:
 #컬럼의  fancy indexing
# 나이를 먼저 보고 싶다 이거지요

In [87]:
info_df.rename(columns= {'name' : '이름'})  

이름  age
a   kim   10
b   lee   20
c  park   30

- name을 이름으로 바꾸고 싶어요

In [89]:
info_df = info_df.rename(columns= {'name' : '이름'}) 

In [90]:
info_df

이름  age
a   kim   10
b   lee   20
c  park   30

- 바꾼 값을 영구적으로 저장하고 싶을때 사용함 ,,, 굳이 바꾸고 싶지 않을 경우에는 데프 인포에 넣을 필요가 없긴 함 

In [91]:
info_df.rename(columns= {'이름' : 'last_name'}, inplace=True)  

In [92]:
info_df

last_name  age
a       kim   10
b       lee   20
c      park   30

In [94]:
excel = pd.read_excel('data/DAMF2.xlsx')

- 컴퓨터에 있는 엑셀 파일을 불러 올 수 있다

In [95]:
excel[['이름','github']]

이름          github
0   오창희         5chang2
1   권기남          kka712
2   김광성         kgs3770
3   김승현         wnshite
4   김윤식     rladbstlr87
5   김주성       darkmonke
6   민예린    Yerineeeee98
7   박선민      manimo1234
8   박소리         alslsol
9   박수빈     vivianpark8
10  박수현       iam-Aerin
11  신효진        DSVIT100
12  양다희        dahee325
13  이유진         eyoojin
14  이주현        Lejuhyun
15  임서영    seoyoung1203
16  장윤서  jangyunseo4547
17  조중석     Chojungseok
18  최민혁    Minhyeok0330
19  최시언       choisieon
20  황다인        dain0628
21  황성진    seongjin5743

-  필요한 정보만을 받을 수 있다

In [97]:
excel.head()  #앞부분만 간략하게 보여줌

이름       전공                  email       github
0  오창희  소프트웨어공학     oche.edu@gmail.com      5chang2
1  권기남   항공전기전공     rlska213@naver.com       kka712
2  김광성     경제학과      kgs3770@gmail.com      kgs3770
3  김승현     음악학과  tmdgus_skfk@naver.com      wnshite
4  김윤식   중국통상학과     manylong@naver.com  rladbstlr87

In [99]:
excel = pd.read_excel('data/DAMF2.xlsx', sheet_name='menu')
excel.head()  # 시트를 선택해서 볼 수 있음

가게이름   시간                       메뉴  \
0     독립문설렁탕   5분                  설랑탕/불고기   
1        송준옥   8분                 맑은뼈국(국밥)   
2       종로김밥  NaN                       분식   
3  바지락수제비칼국수   8분               수제비,칼국수,김밥   
4      유닭스토리   3분  닭(칼국수, 곰탕, 계장)\n닭갈비치즈덮밥   

                                                 한줄평  
0                             설렁탕이 6천원! / 하지만 웨이팅 있음  
1  보통11,000원/특14,000원 bar형식의 테이블로 3~4명가면 일렬로 앉아야되...  
2            2/12 방문기준 신촌역점은 영업 안했어요! 신촌로터리점은 안가봤어요!  
3  칼국수, 수제비, 칼제비 5,000원 김밥 3,000원 / 자리가 협소해서 2-3팀...  
4                               10,000~11,000원/자리많아요

In [102]:
menu_df = excel[['가게이름','메뉴']]

In [103]:
menu_df.head()

가게이름                       메뉴
0     독립문설렁탕                  설랑탕/불고기
1        송준옥                 맑은뼈국(국밥)
2       종로김밥                       분식
3  바지락수제비칼국수               수제비,칼국수,김밥
4      유닭스토리  닭(칼국수, 곰탕, 계장)\n닭갈비치즈덮밥

In [104]:
menu_df.to_excel('data/sample2.xlsx',index =False)

- 저장 하고 싶은 위치에 저장 할 수 있다

### csv

In [105]:
df = pd.read_csv('data/DAMF2.csv')

In [106]:
df.head()

이름       전공                  email       github
0  오창희  소프트웨어공학     oche.edu@gmail.com      5chang2
1  권기남   항공전기전공     rlska213@naver.com       kka712
2  김광성     경제학과      kgs3770@gmail.com      kgs3770
3  김승현     음악학과  tmdgus_skfk@naver.com      wnshite
4  김윤식   중국통상학과     manylong@naver.com  rladbstlr87

In [107]:
df2 = df[['이름', 'email']]

In [108]:
df2.head()

이름                  email
0  오창희     oche.edu@gmail.com
1  권기남     rlska213@naver.com
2  김광성      kgs3770@gmail.com
3  김승현  tmdgus_skfk@naver.com
4  김윤식     manylong@naver.com

In [109]:
df2.to_csv('data/sample2.cvs')

In [1]:
import pandas as pd
import seaborn as sns

In [3]:
df = sns.load_dataset('penguins')

In [4]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [11]:
# 500g  이상의 펭귄 출력

HP = df['body_mass_g'] >= 500

In [13]:
df[HP].head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
4       3450.0  Female  
5       3650.0    Male

In [ ]:
# Gentoo 종의  flipper_length 평균

In [22]:
df['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [24]:
peng1 = df['species'] == 'Gentoo'

In [25]:
df.loc[peng1 , 'flipper_length_mm'].mean()

np.float64(217.1869918699187)

In [ ]:
# Female ch,,,,종의 bill_length 높은 순 정

In [29]:
FG = df['sex'] == 'Female'
SG = df['species'] == 'Chinstrap'

df.loc[FG & SG].sort_values('bill_length_mm', ascending = False).head(5)

species island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
169  Chinstrap  Dream            58.0           17.8              181.0   
196  Chinstrap  Dream            50.9           17.9              196.0   
178  Chinstrap  Dream            50.5           18.4              200.0   
219  Chinstrap  Dream            50.2           18.7              198.0   
198  Chinstrap  Dream            50.1           17.9              190.0   

     body_mass_g     sex  
169       3700.0  Female  
196       3675.0  Female  
178       3400.0  Female  
219       3775.0  Female  
198       3400.0  Female

In [ ]:
# species(종)별 성별 구분하여 평균 몸무게 출력
 #=> ex) Adelie, Female / Adelie, male / Gentoo, Female...

In [35]:
df['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [37]:
AP = df['species'] == 'Adelie'

GP = df['species'] == 'Gentoo'

CP = df['species'] == 'Chinstrap'

WP = df['sex'] == 'Female'
MP = df['sex'] == 'Male'


In [43]:
print (df.loc[AP & WP, 'body_mass_g'].mean())
print(df.loc[GP & WP, 'body_mass_g'].mean())
print(df.loc[CP & WP, 'body_mass_g'].mean())

3368.8356164383563
4679.741379310345
3527.205882352941


In [44]:
print (df.loc[AP & MP, 'body_mass_g'].mean())
print(df.loc[GP & MP, 'body_mass_g'].mean())
print(df.loc[CP & MP, 'body_mass_g'].mean())

4043.4931506849316
5484.836065573771
3938.970588235294


In [64]:
df_copy = df.copy()
for species in df_copy['species'].unique(): # df_copy['species'].unique()는 ['Adelie' 'Chinstrap' 'Gentoo'] 나오기 때문에 for문을 써서 종별 구분
    for sex in df_copy['sex'].unique()[:2]: # df_copy['sex'].unique()는 ['Male' 'Female' nan] 나오기 때문에 for문을 쓰지만 nan을 쓰지 않고 Female까지만 나올 수 있도록 [:2]를 써서 성별 구분
        con1 = df_copy['species'] == species
        con2 = df_copy['sex'] == sex
        print(f'{species}, {sex}의 평균 몸무게는 ', end = '')
        print(df_copy.loc[con1 & con2, 'body_mass_g'].mean()) # 평균 몸무게 출

Adelie, Male의 평균 몸무게는 4043.4931506849316
Adelie, Female의 평균 몸무게는 3368.8356164383563
Chinstrap, Male의 평균 몸무게는 3938.970588235294
Chinstrap, Female의 평균 몸무게는 3527.205882352941
Gentoo, Male의 평균 몸무게는 5484.836065573771
Gentoo, Female의 평균 몸무게는 4679.741379310345


In [ ]:
# bill_depth 결측치 채우기
# => 같은종 같은섬의 평균으로

In [46]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [49]:
df_c = df.copy()

In [51]:
df_c.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [52]:
df_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [ ]:
# 빌뎁스의 결측치가 어디서 발생했는지 찾고
# 같은 종 같은 섬 공통의 평균을 구해서 넣기 
#

In [62]:
pingu.value_counts()

bill_depth_mm
False    342
True       2
Name: count, dtype: int64

In [63]:
print(df[df['bill_depth_mm'].isnull()])

    species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
3    Adelie  Torgersen             NaN            NaN                NaN   
339  Gentoo     Biscoe             NaN            NaN                NaN   

     body_mass_g  sex  
3            NaN  NaN  
339          NaN  NaN  


In [65]:
df_copy = df.copy()

for species in df_copy['species'].unique(): 
    # df_copy['species'].unique()는 ['Adelie' 'Chinstrap' 'Gentoo'] 나오기 때문에 for문을 써서 종별 구분
    for island in df_copy['island'].unique(): 
        # df_copy['island'].unique()는 ['Torgersen' 'Biscoe' 'Dream'] 나오기 때문에 for문을 써서 섬별 구분
        con1 = df_copy['species'] == species
        con2 = df_copy['island'] == island
        avg = df_copy.loc[con1 & con2, 'bill_depth_mm'].mean() # 같은 종, 같은 섬의 평균
        df_copy.loc[con1 & con2, 'bill_depth_mm'] = df_copy.loc[con1 & con2, 'bill_depth_mm'].fillna(avg) # 결측치 채우기
df_copy

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1      18.700000              181.0   
1    Adelie  Torgersen            39.5      17.400000              186.0   
2    Adelie  Torgersen            40.3      18.000000              195.0   
3    Adelie  Torgersen             NaN      18.429412                NaN   
4    Adelie  Torgersen            36.7      19.300000              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN      14.982114                NaN   
340  Gentoo     Biscoe            46.8      14.300000              215.0   
341  Gentoo     Biscoe            50.4      15.700000              222.0   
342  Gentoo     Biscoe            45.2      14.800000              212.0   
343  Gentoo     Biscoe            49.9      16.100000              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]